@component('mail::message')
# Dear {{ Auth::user()->firstname }} {{ Auth::user()->lastname }}, <br>



Thank you for registering with Japan Remit Finance Co.,Ltd <br>
You can login with you email address (ID) and Password and add Beneficiary till we complete <br>
our KYC (Know Your Customer) Process.<br>
<br>
<br>


If you have any questions, please contact us.<br>
{{ config('app.name') }}

<br>
<br>
<br>
<br>
<br>
Automatically generated by System. PLEASE DO NOT REPLY
@endcomponent
